# CONDA ENVIRONMENT FILE
name: nf_metag
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nextflow
  - nf-core
  - R
  - singularity=3.8.6
  - bwa
  - pigz
  - fastp
  - samtools
  - salmon
  - fastqc
  - multiqc
  - megahit
  - csvtk
  - seqkit
  - axel
