# CONDA ENVIRONMENT FILE
name: nf_metag
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nextflow=23.10.1
  - nf-core
  - R
  - singularity=3.8.6
  - bwa=0.7.17
  - fastp
  - samtools=1.17
  - salmon
  - fastqc
  - multiqc
  - megahit
